services:
  api:
    build: .
    ports:
      - 8000:8000
    env_file:
      - .env

  database:
    image: postgres
    ports:
      - 5000:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=deckkingdb

volumes:
  pgdata:
