name: DigitalOcean droplet deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted 

    steps:
      - uses: actions/checkout@main
      - name: Run
        run: docker compose up -d
